# Generated by Django 3.0.7 on 2021-03-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handlerequests', '0002_auto_20210304_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemTrackingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now_add=True)),
                ('battery_percentage', models.IntegerField()),
                ('cpu_usage', models.FloatField()),
                ('ram_usage', models.FloatField()),
                ('disk_usage', models.FloatField()),
            ],
        ),
    ]
