# Generated by Django 3.0.7 on 2021-03-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handlerequests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
