# Generated by Django 3.0.7 on 2021-03-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handlerequests', '0003_systemtrackingdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebCamImageHandler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
